### ISSUE TITLE
Compress files based on LastWriteTime

### ISSUE THREAD

**Issue by ericclaus14** [thoemmi/7Zip4Powershell#45]
Hello,

This module is working great for me. I am looking to expand how I use it by only adding files to an archive that have been modified in the last day. When I try using the below code, no .7z file is created. Is there some way to accomplish this?

$lastWrite = (Get-Date).AddDays(-1)
Get-ChildItem C:\Temp | Where {$_.LastWriteTime -ge "$LastWrite"} | 
     Compress-7Zip -Format SevenZip -ArchiveFileName "C:\Backup\test.7z" -Password "Password"

Thank you,
Eric

**Comment by synt3k** [comment]
Odd that you would just create this issue, as I am facing the EXACT same problem in my script. I am just trying to compress all files of a single extension that were created in the past 24 hours as part of a backup script, but Compress-7Zip does not appear to support the filtering via the pipeline, so I am looking into just using the standard Compress-Archive cmdlet to create a ZIP file, which is unfortunate. If anyone can solve this issue I would be thrilled to use 7Zip, ideally via this module.

**Comment by thoemmi** [comment]
I could reproduce the issue. Well, actually it's not an issue but the way the Powershell engine passes the filenames to my cmdlet. `Compress-7Zip` gets only the names of the files, but not the full path. To get your example working, you have to select the `FullName` property to `Compress-7Zip`:

```powershell
Get-ChildItem  C:\Temp -File `
  | ? { $_.LastWriteTime -ge $lastWrite } `
  | % { $_.FullName } `
  | Compress-7Zip -ArchiveFileName D:\tmp\7zip\test.7z
```

Please note that I've added the `-File` switch to `Get-ChildItem` because you cannot mix files and directories with `Compress-7Zip`.

**Comment by ericclaus14** [comment]
That worked great. I added the -Recurse flag to the Get-ChildItem command to get files from sub-directories. Thanks for the help!
